---
- name: Update Thorfinn device.
  hosts: all
  tasks:
    - name: Install Python Pip
      become: yes
      apt:
        name: ['python3-pip', 'python3-setuptools']

    - name: Get latest controller module.
      copy: 
        src: controller
        dest: ~/

    - name: Install Python requirements.
      pip:
        requirements: ~/controller/requirements.txt
        executable: pip3
      