---
- name: Update Thorfinn device.
  hosts: all
  tasks:
    - name: Get latest controller module.
      copy: 
        src: controller
        dest: ~/

    - name: Install Python requirements.
      pip:
        requirements: ~/controller/requirements.txt
        executable: pip3
      