---
- name: Update Thorfinn device.
  hosts: all
  become: yes
  tasks:
    - name: Set a Hostname
      ansible.builtin.hostname:
        name: thorfinn
        
    - name: Get latest controller module.
      copy: 
        src: controller
        dest: ~/
  