---
- name: Update Thorfinn device.
  hosts: all
  become: yes
  tasks:
    - name: Set a Hostname
      hostname:
        name: thorfinn

    - name: Get latest controller module.
      copy: 
        src: controller
        dest: ~/
  