---
- name: OTA update Thorfinn edge device for Canute OS.
  hosts: local

  tasks:
    - name: Get the latest controller module code.
      copy: 
        src: controller
        dest: ~/

    - name: Install controller module code python requirements.
      pip:
        requirements: ~/controller/requirements.txt
        executable: pip3
      