---
- name: Provision Thorfinn edge device for Canute OS.
  hosts: remote
  
  become: yes
  remote_user: pi
  gather_facts: no

  tasks:
    - name: Update device hostname.
      hostname:
        name: thorfinn

    - name: Install Ansible.
      become: yes
      apt:
        name: ansible
        state: latest

    - name: Install Git.
      apt:
        name: git
        state: latest

    - name: Add OTA update as a cron job.
      cron:
        user: pi
        name: ota
        minute: "*/5"
        job: "ansible-pull -o -U https://github.com/RangerDigital/canute-things thorfinn-v1/main.yml -i thorfinn-v1/hosts"

