---
- name: Factory provision Thorfinn device.
  hosts: remote
  gather_facts: no
  remote_user: pi

  tasks:
    - name: Set a Hostname
      become: yes
      hostname:
        name: thorfinn

    - name: Install Python Pip
      become: yes
      apt:
        name: ['python3-pip', 'python3-setuptools']

    - name: Install Ansible
      become: yes
      apt:
        name: ansible

    - name: Install Git
      become: yes
      apt:
        name: git

    - name: Add Ansible-Pull to crontab
      cron:
        name: "OTA Update"
        minute: "*/5"
        job: "ansible-pull -o -U https://github.com/RangerDigital/canute-things thorfinn-v1/main.yml -i thorfinn-v1/hosts"

